version: '3.1'

services:
  db:
    image: mysql:8.0
    container_name: api-db
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - .docker/dbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=nest_clean
      - MYSQL_USER=nestuser
      - MYSQL_PASSWORD=nestpass
